/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;
import Backend.Libro;
import java.util.*;
/**
 *
 * @author angel
 */
public class Editador extends javax.swing.JFrame {

    /**
     * Creates new form Editador
     */
    private Libro libro_editar;
    private int indice;
    private ArrayList<Libro> libros= new ArrayList();
    public Editador() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public Editador(Libro libro_editar,ArrayList<Libro> libros, int indice) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.libro_editar=libro_editar;
        this.libros=libros;
        this.indice=indice;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Editar_nombre = new javax.swing.JButton();
        Editar_Autor = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Salir = new javax.swing.JButton();
        Editar_Año = new javax.swing.JButton();
        Editar_Paginas = new javax.swing.JButton();
        Editar_Generos = new javax.swing.JButton();
        Cantidad = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Editar_nombre.setText("Nombre");
        Editar_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Editar_nombreActionPerformed(evt);
            }
        });
        getContentPane().add(Editar_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 34, -1, -1));

        Editar_Autor.setText("Autor");
        Editar_Autor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Editar_AutorActionPerformed(evt);
            }
        });
        getContentPane().add(Editar_Autor, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 69, -1, -1));

        jLabel6.setText("Seleccione que desea editar");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 211, -1));

        Salir.setBackground(new java.awt.Color(255, 51, 51));
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 255, -1, -1));

        Editar_Año.setText("Año de publicacion");
        Editar_Año.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Editar_AñoActionPerformed(evt);
            }
        });
        getContentPane().add(Editar_Año, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 104, -1, -1));

        Editar_Paginas.setText("Numero de paginas");
        Editar_Paginas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Editar_PaginasActionPerformed(evt);
            }
        });
        getContentPane().add(Editar_Paginas, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 174, -1, -1));

        Editar_Generos.setText("Generos");
        Editar_Generos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Editar_GenerosActionPerformed(evt);
            }
        });
        getContentPane().add(Editar_Generos, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 139, -1, -1));

        Cantidad.setText("Cantidad");
        Cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantidadActionPerformed(evt);
            }
        });
        getContentPane().add(Cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 209, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 390, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Editar_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Editar_nombreActionPerformed
        Editar_nombre nombre = new Editar_nombre(libros,libro_editar,indice);
        nombre.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Editar_nombreActionPerformed

    private void Editar_AutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Editar_AutorActionPerformed
        Editar_autor autor = new Editar_autor(libros,libro_editar,indice);
        autor.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Editar_AutorActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        InicioAdmin admin= new InicioAdmin();
        admin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SalirActionPerformed

    private void Editar_AñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Editar_AñoActionPerformed
        Editar_Año año = new Editar_Año(libros,libro_editar,indice);
        año.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Editar_AñoActionPerformed

    private void Editar_PaginasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Editar_PaginasActionPerformed
        Editar_Paginas paginas = new Editar_Paginas(libros,libro_editar,indice);
        paginas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Editar_PaginasActionPerformed

    private void Editar_GenerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Editar_GenerosActionPerformed
        Editar_Generos generos = new Editar_Generos(libros,libro_editar,indice);
        generos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Editar_GenerosActionPerformed

    private void CantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantidadActionPerformed
        Editar_cantidad cantidad = new Editar_cantidad(libros,libro_editar,indice);
        cantidad.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CantidadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cantidad;
    private javax.swing.JButton Editar_Autor;
    private javax.swing.JButton Editar_Año;
    private javax.swing.JButton Editar_Generos;
    private javax.swing.JButton Editar_Paginas;
    private javax.swing.JButton Editar_nombre;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
