/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;
import java.util.*;
import Backend.*;
import static Interfaces.Frontend.cantidad_usuario;

import javax.swing.JOptionPane;
/**
 *
 * @author Equipo 7
 */
public class Frontend_Admin extends javax.swing.JFrame {

    /**
     * Creates new form Frontend_Admin
     */
    static public boolean encontrado=false;
    int indice,libro_encontrado=0;
    static int cantidad_usuario=0;
    Libro libro_pedir,libro_fav;
    InicioAdmin inicio= new InicioAdmin();
    private static ArrayList<Favoritos> favoritos= new ArrayList();
    private ArrayList<Libro> libros = new ArrayList();
    static private ArrayList<Libro> libros_pedir = new ArrayList();
    public Frontend_Admin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public Frontend_Admin(ArrayList<Libro> libros) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.libros=libros;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Informacion = new javax.swing.JTextArea();
        Cerrar_sesion = new javax.swing.JButton();
        InfoAdmin = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Libros_disponibles = new javax.swing.JTextArea();
        Disponibles = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Buscador = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        Libros = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        favs = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        libross = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        añadir = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        Pedir_prestamo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        librones = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        Buscadorsin = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(67, 113, 248));

        Informacion.setColumns(20);
        Informacion.setRows(5);
        jScrollPane3.setViewportView(Informacion);

        Cerrar_sesion.setText("Cerrar sesion");
        Cerrar_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cerrar_sesionActionPerformed(evt);
            }
        });

        InfoAdmin.setText("Informacion de la cuenta");
        InfoAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Cerrar_sesion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(InfoAdmin)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cerrar_sesion)
                    .addComponent(InfoAdmin))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cuenta", jPanel1);

        jPanel2.setBackground(new java.awt.Color(67, 113, 248));

        Libros_disponibles.setColumns(20);
        Libros_disponibles.setRows(5);
        jScrollPane1.setViewportView(Libros_disponibles);

        Disponibles.setText("Consultar libros disponibles");
        Disponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisponiblesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(Disponibles)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Disponibles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        jTabbedPane1.addTab("Libros", jPanel2);

        jPanel3.setBackground(new java.awt.Color(67, 113, 248));

        jLabel3.setForeground(new java.awt.Color(216, 213, 34));
        jLabel3.setText("Nombre del libro:");

        Buscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscadorActionPerformed(evt);
            }
        });
        Buscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BuscadorKeyReleased(evt);
            }
        });

        Libros.setColumns(20);
        Libros.setRows(5);
        jScrollPane6.setViewportView(Libros);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Buscador, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Buscador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Buscar", jPanel3);

        jPanel4.setBackground(new java.awt.Color(67, 113, 248));

        favs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                favsKeyReleased(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(216, 213, 34));
        jLabel1.setText("Añadir libros a favoritos");

        libross.setColumns(20);
        libross.setRows(5);
        jScrollPane2.setViewportView(libross);

        jLabel2.setForeground(new java.awt.Color(216, 213, 34));
        jLabel2.setText("Nombre:");

        añadir.setText("Añadir a favoritos");
        añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(favs, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(añadir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(favs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(añadir)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Favoritos", jPanel4);

        jPanel5.setBackground(new java.awt.Color(67, 113, 248));

        Pedir_prestamo.setText("Pedir prestamo");
        Pedir_prestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pedir_prestamoActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(216, 213, 34));
        jLabel4.setText("Libros disponibles:");

        librones.setColumns(20);
        librones.setRows(5);
        jScrollPane8.setViewportView(librones);

        jLabel5.setForeground(new java.awt.Color(216, 213, 34));
        jLabel5.setText("Ingrese el nombre del libro que desea pedir");

        Buscadorsin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscadorsinActionPerformed(evt);
            }
        });
        Buscadorsin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BuscadorsinKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pedir_prestamo)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(Buscadorsin, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(2, 2, 2)
                .addComponent(Buscadorsin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Pedir_prestamo)
                .addGap(99, 99, 99))
        );

        jTabbedPane1.addTab("Prestamos", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Cerrar_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cerrar_sesionActionPerformed
        InicioAdmin salir = new InicioAdmin();
        salir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Cerrar_sesionActionPerformed

    private void DisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisponiblesActionPerformed
        String mostrar="";
        if(libros.size()==0){
            JOptionPane.showMessageDialog(null,"Aun no tenemos libros U.u");
        }else{
            for(int i=0;i<libros.size();i++){
            mostrar+= libros.get(i).toString()+"\n\n";
            }
            Libros_disponibles.setText(mostrar);
            }
    }//GEN-LAST:event_DisponiblesActionPerformed

    private void BuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscadorActionPerformed

    private void BuscadorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscadorKeyReleased
        Libros.setText("");
        String mostrar = "";
        for(int i=0;i<libros.size();i++){
            if(libros.get(i).buscador(Buscador.getText()))
            mostrar += libros.get(i).toString()+"\n\n";
        }
        Libros.setText(mostrar);
    }//GEN-LAST:event_BuscadorKeyReleased

    private void Pedir_prestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pedir_prestamoActionPerformed
        boolean prestado=false;
        
        Pedi pedir= new Pedi(new Prestamos_admin(),libros,libro_pedir,indice);
        prestado=pedir.pedir();
        
    }//GEN-LAST:event_Pedir_prestamoActionPerformed

    private void BuscadorsinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscadorsinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscadorsinActionPerformed

    private void BuscadorsinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscadorsinKeyReleased
        librones.setText("");
        String mostrar = "";
        for(int i=0;i<libros.size();i++){
            if(libros.get(i).buscador(Buscadorsin.getText())){
                indice=i;
                libro_pedir=libros.get(i);
                mostrar += libros.get(i).toString()+"\n\n";
                encontrado=true;
            }
                
            
        }
        librones.setText(mostrar);
    }//GEN-LAST:event_BuscadorsinKeyReleased

    private void InfoAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoAdminActionPerformed
        String mostrar="";
        for(int i=0;i<cantidad_usuario;i++){
            if(favoritos.get(i).usuario.equals(inicio.user)){
                mostrar+=favoritos.get(i).toString()+"\n\n";
            }
        }
        String prestamos = "Prestamos maximos: infinitor";
        String cuenta = "Tipo de cuenta: Admin";
        String usuario = "Usuario:"+inicio.user;
        String mensaje = "CUENTA EN TISTA´S BOOKS";
        String favoritoos= "Libros favoritos:\n"+mostrar;
        Informacion.setText(mensaje + "\n\n" + usuario + "\n" + cuenta + "\n" + prestamos+"\n"+favoritoos);
    }//GEN-LAST:event_InfoAdminActionPerformed

    private void favsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_favsKeyReleased
        libross.setText("");
        libro_encontrado=0;
        String mostrar = "";
        for(int i=0;i<libros.size();i++){
            if(libros.get(i).buscador(favs.getText())){
                indice=i;
                libro_fav=libros.get(i);
                mostrar += libros.get(i).toString()+"\n\n";
                encontrado=true;
                libro_encontrado++;
            }

        }
        libross.setText(mostrar);
    }//GEN-LAST:event_favsKeyReleased

    private void añadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirActionPerformed
        if(libro_encontrado>=2){
            JOptionPane.showMessageDialog(null,"Solo puedes añadir un libro a la vez");
        }else{
            Favoritos favorito = new Favoritos(inicio.user);
            favoritos.add(favorito);
            favorito.añadir(libro_fav);
            cantidad_usuario++;
            JOptionPane.showMessageDialog(null,"Libro añadido a tus favoritos");

        }
    }//GEN-LAST:event_añadirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frontend_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frontend_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frontend_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frontend_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frontend_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Buscador;
    private javax.swing.JTextField Buscadorsin;
    private javax.swing.JButton Cerrar_sesion;
    private javax.swing.JButton Disponibles;
    private javax.swing.JButton InfoAdmin;
    private javax.swing.JTextArea Informacion;
    private javax.swing.JTextArea Libros;
    private javax.swing.JTextArea Libros_disponibles;
    private javax.swing.JButton Pedir_prestamo;
    private javax.swing.JButton añadir;
    private javax.swing.JTextField favs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea librones;
    private javax.swing.JTextArea libross;
    // End of variables declaration//GEN-END:variables
}
