/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Backend.Libro;
import static Interfaces.InicioAdmin.libros;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.util.Scanner;
import java.io.*;
import Backend.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Admin
 */
public class InicioSesion extends javax.swing.JFrame {
    private static Scanner sc,sd;
    private static int intentos;
    private String pwd;
    static String user;
    private boolean entrar;
    private ArrayList<Favoritos> favs= new ArrayList();
    public InicioSesion() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public InicioSesion(ArrayList<Favoritos> favs) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.favs=favs;
    }

    public static void setIntentos(int intentos) {
        InicioSesion.intentos = intentos;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Salir = new javax.swing.JButton();
        Ingresar = new javax.swing.JButton();
        Admin = new javax.swing.JButton();
        Contrasena = new javax.swing.JPasswordField();
        Usuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Registrate = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Salir.setBackground(new java.awt.Color(255, 51, 51));
        Salir.setText("Volver");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        Ingresar.setText("Ingresar");
        Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarActionPerformed(evt);
            }
        });
        getContentPane().add(Ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 80, -1));

        Admin.setBackground(new java.awt.Color(255, 153, 0));
        Admin.setText("Admin");
        Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminActionPerformed(evt);
            }
        });
        getContentPane().add(Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, -1));

        Contrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContrasenaActionPerformed(evt);
            }
        });
        getContentPane().add(Contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 130, -1));

        Usuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 130, -1));

        jLabel1.setText("Usuario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 50, -1));

        jLabel2.setText("Contraseña:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(217, 214, 33));
        jLabel3.setText("Biblioteca Tista´s Books");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        Registrate.setBackground(new java.awt.Color(0, 153, 255));
        Registrate.setText("Registrarse");
        Registrate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrateActionPerformed(evt);
            }
        });
        getContentPane().add(Registrate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        jPanel2.setBackground(new java.awt.Color(69, 114, 249));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    static ArrayList<Libro> libros = new ArrayList();
    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed

        Menu_usario back= new Menu_usario();
        back.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SalirActionPerformed

    private void IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarActionPerformed
        InicioAdmin admin= new InicioAdmin();
        InicioPremium premium= new InicioPremium();
        
        FileReader fr = null;
        try{
            int noLineas = 0, i = 0,noLineas2=0;
            String [] usuarios = null, contraseñas=null;
            String linea, linea2;
            
            sc = new Scanner(new File("src\\main\\java\\IniciosDeSesion\\Usuarios.txt"));
            File archivo = new File("src\\main\\java\\IniciosDeSesion\\Usuarios.txt");
            fr = new FileReader(archivo);
            BufferedReader br = new BufferedReader(fr);
       
            try{
                while((linea=br.readLine()) != null){
                noLineas++;
                } 
            }
            catch(IOException e){     
                Logger.getLogger(InicioSesion.class.getName()).log(Level.SEVERE,null,e);
            }
            sd = new Scanner(new File("src\\main\\java\\IniciosDeSesion\\Contraseñas.txt"));
            File archiv = new File("src\\main\\java\\IniciosDeSesion\\Contraseñas.txt");
            fr = new FileReader(archiv);
            BufferedReader brr = new BufferedReader(fr);
       
            try{
                while((linea2=brr.readLine()) != null){
                noLineas2++;
                } 
            }
            catch(IOException e){
                Logger.getLogger(InicioSesion.class.getName()).log(Level.SEVERE,null,e);
            }
            
            usuarios = new String[noLineas];
            contraseñas = new String[noLineas2];
            while(sc.hasNextLine()){
                usuarios[i++] = sc.nextLine();
            }
            i=0;
            while(sd.hasNextLine()){
                contraseñas[i++] = sd.nextLine();
            }
            intentos++;
            
            user = Usuario.getText();
            pwd = Contrasena.getText();
            
            ValidarInfo val = new ValidarInfo();
            entrar = val.InfoUsuario(usuarios,contraseñas, user, pwd, intentos);
        
        }   
        catch(FileNotFoundException e){
            Logger.getLogger(InicioSesion.class.getName()).log(Level.SEVERE,null,e);
        }
        
        finally{
            try{
                fr.close();
            }
            catch(IOException e){
                Logger.getLogger(InicioSesion.class.getName()).log(Level.SEVERE,null,e);
            }
        }
        
        if(libros.isEmpty()&& admin.libros.isEmpty()&& premium.libros.isEmpty()){
        
            libros.add(new Libro("It","Estephen King","Terror/Thriller/Novela/Fantasia Obscura",1244,1986,15));
            libros.add(new Libro("Harry Potter y la cámara secreta","Libro de J. K. Rowling","Novela, Literatura fantástica, Novela de aprendizaje, Alta fantasía, Ficción de aventuras",365,1998,10));
            try {
                File archivin = new File("src\\main\\java\\Libros\\Libros.obj");
                archivin.delete();
                FileOutputStream file= new FileOutputStream("src\\main\\java\\Libros\\Libros.obj",true);
                ObjectOutputStream escribir=new ObjectOutputStream(file);

                for(Libro lib : libros) // For each.
                {
                    escribir.writeObject(lib);
                    escribir.reset();
                }
                    
                
                escribir.close();
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(null,"Error\nNo se ha encontrado el archivo papuu");
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null,"Error\nNo se ha encontrado el archivo papu");
            }
        }else{
            int tamaño=0;
            Administrador adminn= new Administrador();
            try {
                FileInputStream file= new FileInputStream("src\\main\\java\\Libros\\Libros.obj");
                
                ObjectInputStream leer =new ObjectInputStream(file);

                if(!libros.isEmpty()){
                    tamaño=libros.size();
                }else if(!admin.libros.isEmpty()){
                    tamaño=admin.libros.size();
                }
                else if(!premium.libros.isEmpty()){
                    tamaño=premium.libros.size();
                }
                libros.clear();
                int tamaño_final=tamaño+adminn.contador;

                for(int i=0;i<tamaño_final;i++){

                    Libro libro_agregar=(Libro)leer.readObject();

                    libros.add(libro_agregar);

                }
                leer.close();

            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(null,"Error\nNo se ha encontrado el archivo papu");
            } catch(ClassNotFoundException ex){
                JOptionPane.showMessageDialog(null,"Error\nNo se ha encontrado la clase papu");
            }catch (IOException ex) {
                JOptionPane.showMessageDialog(null,ex.getMessage());
            }
            
        }
        if(entrar){
            Bienvenida inicio= new Bienvenida(libros,favs);
            inicio.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_IngresarActionPerformed

    private void ContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContrasenaActionPerformed

    private void UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioActionPerformed

    private void AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminActionPerformed
        InicioAdmin admin=new InicioAdmin();
        admin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AdminActionPerformed

    private void RegistrateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrateActionPerformed
        Registrarse enter= new Registrarse();
        enter.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RegistrateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Admin;
    private javax.swing.JPasswordField Contrasena;
    private javax.swing.JButton Ingresar;
    private javax.swing.JButton Registrate;
    private javax.swing.JButton Salir;
    private javax.swing.JTextField Usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
