/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;
import Backend.Libro;
import static Interfaces.InicioAdmin.libros;
import static Interfaces.InicioSesion.libros;
import java.util.*;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import Backend.*;
/**
 *
 * @author Equipo 7
 */
public class InicioPremium extends javax.swing.JFrame {
    private static Scanner sc,sd;
    private static int intentos;
    private static String  pwd;
    static String user;
    private boolean entrar;
    /**
     * Creates new form InicioPremium
     */
    
    public InicioPremium() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public static void setIntentos(int intentos) {
        InicioPremium.intentos = intentos;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Salir = new javax.swing.JButton();
        Usuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Contraseña = new javax.swing.JPasswordField();
        Ingresar = new javax.swing.JButton();
        Admin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Salir.setBackground(new java.awt.Color(255, 51, 51));
        Salir.setText("Volver");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 238, -1, -1));

        Usuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 108, 130, -1));

        jLabel2.setText("Contraseña:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 148, -1, -1));

        Contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 148, 130, -1));

        Ingresar.setText("Ingresar");
        Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarActionPerformed(evt);
            }
        });
        getContentPane().add(Ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 188, -1, -1));

        Admin.setBackground(new java.awt.Color(255, 153, 0));
        Admin.setText("Admin");
        Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminActionPerformed(evt);
            }
        });
        getContentPane().add(Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 238, -1, -1));

        jLabel1.setText("Usuario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 108, 50, -1));

        jPanel1.setBackground(new java.awt.Color(67, 113, 248));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(216, 213, 34));
        jLabel3.setText("Biblioteca Tista´s Books");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(81, 81, 81))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel3)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    static ArrayList<Libro> libros = new ArrayList();
    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        Menu_usario back= new Menu_usario();
        back.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SalirActionPerformed

    private void UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioActionPerformed

    private void ContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaActionPerformed

    private void IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarActionPerformed
        InicioAdmin admin= new InicioAdmin();
        InicioSesion normal= new InicioSesion();

        FileReader fr = null;
        try{
            int noLineas = 0, i = 0,noLineas2=0;
            String [] usuarios = null, contraseñas=null;
            String linea, linea2;
            
            sc = new Scanner(new File("src\\main\\java\\IniciosDeSesion\\Premium.txt"));
            File archivo = new File("src\\main\\java\\IniciosDeSesion\\Premium.txt");
            fr = new FileReader(archivo);
            BufferedReader br = new BufferedReader(fr);
       
            try{
                while((linea=br.readLine()) != null){
                noLineas++;
                } 
            }
            catch(IOException e){     
                Logger.getLogger(InicioPremium.class.getName()).log(Level.SEVERE,null,e);
            }

            sd = new Scanner(new File("src\\main\\java\\IniciosDeSesion\\Contraseñas_Premium.txt"));
            File archiv = new File("src\\main\\java\\IniciosDeSesion\\Contraseñas_Premium.txt");
            fr = new FileReader(archiv);
            BufferedReader brr = new BufferedReader(fr);
       
            try{
                while((linea2=brr.readLine()) != null){
                noLineas2++;
                } 
            }
            catch(IOException e){
                Logger.getLogger(InicioPremium.class.getName()).log(Level.SEVERE,null,e);
            }
            
            usuarios = new String[noLineas];
            contraseñas = new String[noLineas2];
            while(sc.hasNextLine()){
                usuarios[i++] = sc.nextLine();
            }
            i=0;
            while(sd.hasNextLine()){
                contraseñas[i++] = sd.nextLine();
            }
            intentos++;
            
            user = Usuario.getText();
            pwd = Contraseña.getText();
            
            ValidarInfo val = new ValidarInfo();
            entrar = val.InfoUsuarioPremium(usuarios,contraseñas, user, pwd, intentos);
        
        }   
        catch(FileNotFoundException e){
            Logger.getLogger(InicioPremium.class.getName()).log(Level.SEVERE,null,e);
        }
        
        finally{
            try{
                fr.close();
            }
            catch(IOException e){
                Logger.getLogger(InicioPremium.class.getName()).log(Level.SEVERE,null,e);
            }
        }        

        if(libros.isEmpty()&& normal.libros.isEmpty()&& admin.libros.isEmpty()){
            
            libros.add(new Libro("It","Estephen King","Terror/Thriller/Novela/Fantasia Obscura",1244,1986,15));
            libros.add(new Libro("Harry Potter y la cámara secreta","Libro de J. K. Rowling","Novela, Literatura fantástica, Novela de aprendizaje, Alta fantasía, Ficción de aventuras",365,1998,10));
            try {
                File archivin = new File("src\\main\\java\\Libros\\Libros.obj");
                archivin.delete();
                FileOutputStream file= new FileOutputStream("src\\main\\java\\Libros\\Libros.obj");
                ObjectOutputStream escribir=new ObjectOutputStream(file);

                for(Libro lib : libros) // For each.
                {
                    escribir.writeObject(lib);
                    escribir.reset();
                }
                   
                
                escribir.close();
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(null,"Error\nNo se ha encontrado el archivo papuu");
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null,"Error\nNo se ha encontrado el archivo papu");
            }
        }else{
            int tamaño=0;
            Administrador adminn= new Administrador();
            
            try {
                
                FileInputStream file= new FileInputStream("src\\main\\java\\Libros\\Libros.obj");
                ObjectInputStream leer =new ObjectInputStream(file);
                if(!libros.isEmpty()){
                    tamaño=libros.size();
                }else if(!admin.libros.isEmpty()){
                    tamaño=admin.libros.size();
                }
                else if(!normal.libros.isEmpty()){
                    tamaño=normal.libros.size();
                }
                libros.clear();
                int tamaño_final=tamaño+adminn.contador;
                
                for(int i=0;i<tamaño_final;i++){
                    libros.add( (Libro)leer.readObject() );
                    
                }
                leer.close();
                
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(null,"Error\nNo se ha encontrado el archivo papu");
            } catch(ClassNotFoundException ex){
                JOptionPane.showMessageDialog(null,"Error\nNo se ha encontrado la clase papu");
            }catch (IOException ex) {
                JOptionPane.showMessageDialog(null,ex.getMessage());
            }
            
        }    
        if(entrar){
            Bienvenida_Premium inicio= new Bienvenida_Premium(libros);
            inicio.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_IngresarActionPerformed

    private void AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminActionPerformed
        InicioAdmin admin=new InicioAdmin();
        admin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioPremium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioPremium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioPremium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioPremium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioPremium().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Admin;
    private javax.swing.JPasswordField Contraseña;
    private javax.swing.JButton Ingresar;
    private javax.swing.JButton Salir;
    private javax.swing.JTextField Usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
