/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Backend.Libro;
import static Interfaces.InicioSesion.libros;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.*;
/**
 *
 * @author Admin
 */
public class MejoraPremium extends javax.swing.JFrame {
    private static String user,pwd;

    /**
     * Creates new form MejoraPremium
     */
    ArrayList<Libro> libros= new ArrayList();
    public MejoraPremium() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MejoraPremium = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        UsuarioPremium = new javax.swing.JTextField();
        ContraseñaPremium = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(67, 113, 248));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MejoraPremium.setText("Mejorar");
        MejoraPremium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MejoraPremiumActionPerformed(evt);
            }
        });
        jPanel1.add(MejoraPremium, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 90, -1));

        Salir.setBackground(new java.awt.Color(255, 51, 51));
        Salir.setText("Volver");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        jPanel1.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        UsuarioPremium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioPremiumActionPerformed(evt);
            }
        });
        jPanel1.add(UsuarioPremium, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 130, -1));

        ContraseñaPremium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseñaPremiumActionPerformed(evt);
            }
        });
        jPanel1.add(ContraseñaPremium, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 130, -1));

        jLabel1.setText("Ususario:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, 20));

        jLabel3.setText("Contraseña: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Premium_1.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 150, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsuarioPremiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioPremiumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioPremiumActionPerformed

    private void MejoraPremiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MejoraPremiumActionPerformed
        FileWriter arch = null;
        PrintWriter escribir = null;
        FileWriter arch2 = null;
        PrintWriter escribir2 = null;
        boolean llenado = false;
        user = UsuarioPremium.getText();
        pwd = ContraseñaPremium.getText();
        
        //Primer bloque try para los usuarios
        try{
            File archivo = new File("src\\main\\java\\IniciosDeSesion\\Premium.txt");
            arch = new FileWriter(archivo, true);
            escribir = new PrintWriter(arch);
            
        }
        catch(IOException e){
            Logger.getLogger(Registrarse.class.getName()).log(Level.SEVERE, null, e);
        }
        
        //Segundo bloque try para las contraseñas
        try{
            File archivo2 = new File("src\\main\\java\\IniciosDeSesion\\Contraseñas_Premium.txt");
            arch2 = new FileWriter(archivo2, true);
            escribir2 = new PrintWriter(arch2);
                    
        }
        catch(IOException e){
            Logger.getLogger(Registrarse.class.getName()).log(Level.SEVERE, null, e);
        }
        
        finally{
            try {
                if(user.isEmpty()){
                    llenado = false;
                }
                else if (pwd.isEmpty()){
                    llenado = false;
                }
                
                else {
                        escribir.println(user);
                        escribir2.println(pwd);  
                        llenado = true;
                        arch.close();
                        arch2.close();
                }
            } 
            catch (IOException e) {
                Logger.getLogger(Registrarse.class.getName()).log(Level.SEVERE, null, e);
            }
        }
        
        if(llenado == false){
            JOptionPane.showMessageDialog(null, "Llene todos los campos correctamente", "Registro", JOptionPane.ERROR_MESSAGE);
        }
        
        else{
            JOptionPane.showMessageDialog(null,"Su cuenta ha sido mejorada exitosamente", "Mejora a Premium", JOptionPane.INFORMATION_MESSAGE);
            InicioPremium premium = new InicioPremium();
            premium.setVisible(true);
            this.setVisible(false);    
        }                          
    }//GEN-LAST:event_MejoraPremiumActionPerformed

    private void ContraseñaPremiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraseñaPremiumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaPremiumActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        Frontend biblioteca= new Frontend();
        biblioteca.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MejoraPremium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MejoraPremium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MejoraPremium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MejoraPremium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MejoraPremium().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ContraseñaPremium;
    private javax.swing.JButton MejoraPremium;
    private javax.swing.JButton Salir;
    private javax.swing.JTextField UsuarioPremium;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
