/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Registrarse extends javax.swing.JFrame {
    private static String user,pwd;

    /**
     * Creates new form Registrarse
     */
    public Registrarse() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegistrarButton = new javax.swing.JButton();
        NombreUsuario = new javax.swing.JTextField();
        Contrasena = new javax.swing.JTextField();
        VolverButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegistrarButton.setText("Registrar");
        RegistrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(RegistrarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        NombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(NombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 140, -1));

        Contrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContrasenaActionPerformed(evt);
            }
        });
        getContentPane().add(Contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 140, -1));

        VolverButton.setBackground(new java.awt.Color(255, 51, 51));
        VolverButton.setText("Volver");
        VolverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverButtonActionPerformed(evt);
            }
        });
        getContentPane().add(VolverButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel2.setText("Contraseña:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(216, 213, 34));
        jLabel3.setText("Binvenido al registro");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 230, 30));

        jPanel1.setBackground(new java.awt.Color(67, 113, 248));

        jLabel1.setText("Usuario:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel1)
                .addContainerGap(277, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel1)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreUsuarioActionPerformed

    private void ContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContrasenaActionPerformed

    private void RegistrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarButtonActionPerformed
        FileWriter arch = null;
        PrintWriter escribir = null;
        FileWriter arch2 = null;
        PrintWriter escribir2 = null;
        boolean llenado = false;
        user = NombreUsuario.getText();
        pwd = Contrasena.getText();
        
        //Primer bloque try para los usuarios
        try{
            File archivo = new File("src\\main\\java\\IniciosDeSesion\\Usuarios.txt");
            arch = new FileWriter(archivo, true);
            escribir = new PrintWriter(arch);
            
        }
        catch(IOException e){
            Logger.getLogger(Registrarse.class.getName()).log(Level.SEVERE, null, e);
        }
        
        //Segundo bloque try para las contraseñas
        try{
            File archivo2 = new File("src\\main\\java\\IniciosDeSesion\\Contraseñas.txt");
            arch2 = new FileWriter(archivo2, true);
            escribir2 = new PrintWriter(arch2);
                    
        }
        catch(IOException e){
            Logger.getLogger(Registrarse.class.getName()).log(Level.SEVERE, null, e);
        }
        
        finally{
            try {
                if(user.isEmpty()){
                    llenado = false;
                }
                else if (pwd.isEmpty()){
                    llenado = false;
                }
                
                else {
                        escribir.println(user);
                        escribir2.println(pwd);  
                        llenado = true;
                        arch.close();
                        arch2.close();
                }
            } 
            catch (IOException e) {
                Logger.getLogger(Registrarse.class.getName()).log(Level.SEVERE, null, e);
            }
        }
        
        if(llenado == false){
            JOptionPane.showMessageDialog(null, "Llene todos los campos correctamente", "Registro", JOptionPane.ERROR_MESSAGE);
        }
        
        else{
            JOptionPane.showMessageDialog(null, "Se ha registrado correctamente" , "Registro", JOptionPane.INFORMATION_MESSAGE);
            InicioSesion ini = new InicioSesion();
            ini.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_RegistrarButtonActionPerformed

    private void VolverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverButtonActionPerformed
        InicioSesion ini = new InicioSesion();
        ini.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VolverButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Registrarse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Contrasena;
    private javax.swing.JTextField NombreUsuario;
    private javax.swing.JButton RegistrarButton;
    private javax.swing.JButton VolverButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
